# Generated by Django 2.2.5 on 2019-09-02 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_name', models.CharField(max_length=100)),
                ('Agent_id', models.IntegerField()),
                ('bucket_no', models.IntegerField()),
                ('Phone_no', models.IntegerField()),
                ('team_leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent.Agent')),
            ],
        ),
    ]
